name: lasovrana
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
# 1.0.2+2 IOS
environment:
  sdk: ^3.5.4

dependencies:
  animated_custom_dropdown: ^3.0.0
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.18
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_polyline_points: ^2.1.0
  flutter_riverpod: ^2.4.6
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  http: ^1.1.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
